server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.2.103:3306/course
      username: root
      password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*